{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "model-network-allowed.yaml",
    "model-network-denied.yaml"
  ],
  "configMapGenerator": [
    {
      "name": "model-network-check",
      "files": [
        "check.py"
      ]
    }
  ]
}
