{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "namespace": "intro-openshift-ai",
  "resources": [
    "runtime.json",
    "service.json",
    "network.json"
  ],
  "configMapGenerator": [
    {
      "name": "image-generator-code",
      "files": [
        "server.py"
      ]
    }
  ],
  "generatorOptions": {
    "disableNameSuffixHash": true
  }
}
