apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: model-server
  namespace: intro-openshift-ai
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: intro-openshift-ai
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: synology-iscsi-storage
