{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../storage/base",
    "serving-runtime.yaml",
    "model-serving.yaml",
    "model-network-policy.yaml"
  ]
}
