FROM registry.redhat.io/ubi9/python-312@sha256:e81459cecdf1090ec959ff184e28261ffa426f66084622285545bebe4b2fcb22
WORKDIR /app
COPY src/ /app/
COPY prompts/assistant.md /app/assistant.md
EXPOSE 8080
USER 1001
CMD ["python3", "-B", "/app/server.py"]
