{
  "apiVersion": "kustomize.config.k8s.io/v1beta1",
  "kind": "Kustomization",
  "resources": [
    "../lab-model",
    "../../chatbot/base"
  ],
  "namespace": "intro-openshift-ai",
  "patches": [
    {
      "path": "chatbot-settings.yaml"
    }
  ]
}
