{
  "apiVersion": "serving.kserve.io/v1beta1",
  "kind": "InferenceService",
  "metadata": {
    "name": "command-helper"
  },
  "spec": {
    "predictor": {
      "nodeSelector": {
        "kubernetes.io/hostname": "gpu-worker-01"
      },
      "securityContext": {
        "fsGroup": 1000000000,
        "fsGroupChangePolicy": "OnRootMismatch"
      }
    }
  }
}
